[package]
name = "ml_rust"
version = "0.1.0"
authors = ["Chen Liang <chen.liang.mail@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
